# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: yorty
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: polly-id3
# "service" is the name of this project. This will also be added to your AWS resource names.
service: polly-id3

provider:
  name: aws
  runtime: nodejs22.x
  environment:
    S3_BUCKET_NAME: yorty-s3-french
    OUTPUT_FORMAT: mp3
    VOICE_ID: Lea
    LANGUAGE_CODE: fr-FR
    SNS_TOPIC_ARN: 
      Fn::GetAtt: [PollyTaskCompletedTopic, TopicArn]
    POLLY_ENGINE: generative
    TEXT_TYPE: ssml
    MAX_RETRY_ATTEMPTS: 3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "polly:*"
      Resource: "*"
    - Effect: Allow
      Action:
        - "sns:PutDataProtectionPolicy"
        - "sns:Publish"
        - "sns:DeleteTopic"
        - "sns:Subscribe"
        - "sns:ConfirmSubscription"
      Resource: 
        Fn::GetAtt: [PollyTaskCompletedTopic, TopicArn]
    - Effect: Allow
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
        - "s3:DeleteObject"
        - "s3:ListBucket"
        - "s3:HeadObject"
        - "s3:ListObjectsV2"
      Resource: "arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME}/*"
    - Effect: Allow
      Action:
        - "s3:ListBucket"
      Resource: "arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME}"

functions:
  id3:
    handler: id3.handler
    timeout: 900
    memorySize: 1024
  id3PollyTaskCompleted:
    handler: id3.pollyTaskCompleted
    events:
      - sns:
          topicName: pollyid3PollyTaskCompleted
  updateId3Metadata:
    handler: id3.updateId3Metadata
    timeout: 900
    memorySize: 1024

resources:
  Resources:
    PollyTaskCompletedTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: pollyid3PollyTaskCompleted
        DisplayName: Polly Task Completed Notifications
        Tags:
          - Key: Service
            Value: ${self:service}
          - Key: Purpose
            Value: Polly task completion notifications
