# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: yorty
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: polly-id3
# "service" is the name of this project. This will also be added to your AWS resource names.
service: polly-id3

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    TIMEOUT: ${env:TIMEOUT, '120'}
    TIMEOUT_BULK: ${env:TIMEOUT_BULK, '900'}
    MEMORY_SIZE: ${env:MEMORY_SIZE, '512'}
    MEMORY_SIZE_BULK: ${env:MEMORY_SIZE_BULK, '1024'}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}
    VOICE_ID: ${env:VOICE_ID, 'Lea'}
    LANGUAGE_CODE: ${env:LANGUAGE_CODE, 'fr-FR'}
    SNS_TOPIC_ARN: 
      Fn::GetAtt: [PollyTaskCompletedTopic, TopicArn] # TODO: create a topic in the template
    POLLY_ENGINE: ${env:POLLY_ENGINE, 'standard'}
    TEXT_TYPE: ${env:TEXT_TYPE, 'text'}
    MAX_RETRY_ATTEMPTS: ${env:MAX_RETRY_ATTEMPTS, '3'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "polly:*"
      Resource: "*"
    - Effect: Allow
      Action:
        - "sns:PutDataProtectionPolicy"
        - "sns:Publish"
        - "sns:DeleteTopic"
        - "sns:Subscribe"
        - "sns:ConfirmSubscription"
      Resource: "${self:provider.environment.SNS_TOPIC_ARN}"
    - Effect: Allow
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
        - "s3:DeleteObject"
        - "s3:ListBucket"
        - "s3:HeadObject"
        - "s3:ListObjectsV2"
      Resource: "arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME}/*"
    - Effect: Allow
      Action:
        - "s3:ListBucket"
      Resource: "arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME}"

functions:
  id3:
    handler: src/id3.handler
    timeout: ${self:provider.environment.TIMEOUT}
    memorySize: ${self:provider.environment.MEMORY_SIZE}
  id3PollyTaskCompleted:
    handler: src/id3.pollyTaskCompleted
    timeout: ${self:provider.environment.TIMEOUT}
    memorySize: ${self:provider.environment.MEMORY_SIZE}
    events:
      - sns:
          arn: !Ref PollyTaskCompletedTopic
          topicName: PollyTaskCompletedTopic
  updateId3Metadata:
    handler: src/id3.updateId3Metadata
    timeout: ${self:provider.environment.TIMEOUT_BULK}
    memorySize: ${self:provider.environment.MEMORY_SIZE_BULK}

resources:
  Resources:
    PollyTaskCompletedTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: PollyTaskCompletedTopic

